#!/bin/bash
banner(){
clear
echo -e "\e[32m▄▄▌ ▐ ▄▌.▄▄ ·  ▄▄▄· ▄▄·       ·▄▄▄▄      
██· █▌▐█▐█ ▀. ▐█ ▄█▐█ ▌▪▪     ██▪ ██     
██▪▐█▐▐▌▄▀▀▀█▄ ██▀·██ ▄▄ ▄█▀▄ ▐█· ▐█▌    
▐█▌██▐█▌▐█▄▪▐█▐█▪·•▐███▌▐█▌.▐▌██. ██     
 ▀▀▀▀ ▀▪ ▀▀▀▀ .▀   ·▀▀▀  ▀█▄▀▪▀▀▀▀▀•  \e[0m"
}
banner
while :;
do
echo -n "wsp> "
read opc
c=$(echo "$opc" | awk '{print $1}')
i=$(echo "$opc" | awk '{print $2}')
if [[ $c == "coding" ]];
then
sleep 1
echo -e "\e[32m[+]\e[0m exploiting vulnerability"
echo -e " |-\e[31m failed\e[0m"
sleep 1
echo " |"
sleep 1
echo -e " |-\e[32m sucess\e[0m"
sleep 5
echo -e "\e[1;34m[+]\e[0m searching for code page "
echo -e " |-\e[32m whatsapp.com \e[0m scan.."
sleep 1
echo " |"
sleep 1
echo -e " |-\e[32m v.whatsapp.com \e[0m granted"
sleep 3
echo -e "\e[32m[+]\e[0m adding the indicated code \e[32m/$i\e[0m"
echo -e " |-\e[32m opening\e[0m"
sleep 4
#python -m webbrowser -n https://v.whatsapp.com/$i?s=1
elif [[ $c == "answer" ]]
then
sleep 1
echo -e "\e[32m[+]\e[0m exploiting vulnerability"
sleep 1
echo " |"
sleep 1
echo -e " |-\e[32m sucess\e[0m"
sleep 5
echo -e "\e[1;34m[+]\e[0m searching for answer page "
echo -e " |-\e[32m whatsapp.com \e[0m scan.."
sleep 1
echo " |"
sleep 3
echo -e " |-\e[32m web.whatsapp.com \e[0m granted"
sleep 1
echo " |"
sleep 1
echo -en "\e[31m[!]\e[0m message to forge "
read msg
sleep 1
echo " |"
sleep 1
echo -e "\e[32m[+]\e[0m command console attack\e[0m "
sleep 2
echo -e ' |-\e[32m copy and paste to console\e[0m Java Script'
sleep 3
for i in $(seq 1 60); do echo -en "_" ; done ; echo -e ""
echo -e "
clear();
console.log('▄▄▌ ▐ ▄▌.▄▄ ·  ▄▄▄· ▄▄·       ·▄▄▄▄');
console.log('██· █▌▐█▐█ ▀. ▐█ ▄█▐█ ▌▪▪     ██▪ ██');
console.log('██▪▐█▐▐▌▄▀▀▀█▄ ██▀·██ ▄▄ ▄█▀▄ ▐█· ▐█▌');
console.log('▐█▌██▐█▌▐█▄▪▐█▐█▪·•▐███▌▐█▌.▐▌██. ██');
console.log(' ▀▀▀▀ ▀▪ ▀▀▀▀ .▀   ·▀▀▀  ▀█▄▀▪▀▀▀▀▀• ');
console.log('\e[32mWsP CoD\e[0m'); 
console.table('\e[2mFake messages to responder on WhatsApp\e[0m');
e.__x_quotedMsg.body = '\e[2m$msg\e[0m';
e.__x_quotedStanzaID = e.__x_quotedStanzaID + '\e[2m_\e[0m';
"
for i in $(seq 1 60); do echo -en "_" ; done ; echo -e ""
sleep 1
python -m webbrowser -n https://web.whatsapp.com/
elif [[ $c == "help" ]]
then
echo -e "\e[32m\t WsP CoD help \e[0m"
echo
echo -e "coding \t \e[2m<code>\e[0m exploit vulnerability"
echo -e "answer \t \e[2m<message>\e[0m exploit vulnerability"
echo -e "banner \t show banner "
echo -e "exit \t exit wspcod"
echo
elif [[ $c == "banner" ]]
then
banner
elif [[ $c == "exit" ]]
then
echo -e "\e[31m[exit]\e[0m "
exit
else 
echo "help"
fi
done
