#!/bin/bash
trap ctrl_c INT
ctrl_c(){ echo -n ""; }
banner(){
clear
echo -e "\e[32m▄▄▌ ▐ ▄▌.▄▄ ·  ▄▄▄· ▄▄·       ·▄▄▄▄      
██· █▌▐█▐█ ▀. ▐█ ▄█▐█ ▌▪▪     ██▪ ██     
██▪▐█▐▐▌▄▀▀▀█▄ ██▀·██ ▄▄ ▄█▀▄ ▐█· ▐█▌    
▐█▌██▐█▌▐█▄▪▐█▐█▪·•▐███▌▐█▌.▐▌██. ██     
 ▀▀▀▀ ▀▪ ▀▀▀▀ .▀   ·▀▀▀  ▀█▄▀▪▀▀▀▀▀•  \e[0m"
}
banner
while :;
do
echo -n "wsp> "
read opc
c=$(echo "$opc" | awk '{print $1}')
i=$(echo "$opc" | awk '{print $2}')
if [[ $c == "coding" ]];
then
sleep 1
echo -e "\e[32m[+]\e[0m exploiting vulnerability"
echo -e " |-\e[31m failed\e[0m"
sleep 1
echo " |"
sleep 1
echo -e " |-\e[32m sucess\e[0m"
sleep 5
echo -e "\e[1;34m[+]\e[0m searching for code page "
echo -e " |-\e[32m whatsapp.com \e[0m scan.."
sleep 1
echo " |"
sleep 1
echo -e " |-\e[32m v.whatsapp.com \e[0m granted"
sleep 3
echo -e "\e[32m[+]\e[0m adding the indicated code \e[32m/$i\e[0m"
echo -e " |-\e[32m opening\e[0m"
sleep 4
python -m webbrowser -n https://v.whatsapp.com/$i?s=1
elif [[ $c == "help" ]]
then
echo -e "\e[32m\t WsP CoD help \e[0m"
echo
echo -e "coding \t \e[2m<code>\e[0m exploit vulnerability"
echo -e "banner \t show banner "
echo -e "exit \t exit wspcod"
echo
elif [[ $c == "banner" ]]
then
banner
elif [[ $c == "exit" ]]
then
echo -e "\e[31m[exit]\e[0m "
exit
else 
echo "help"
fi
done
